version: "3.5"

services:

  sanic_template:
    container_name: sanic_template
    restart: always
    image: sanic_template:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8801:8001"
    environment:
      - VAR1=${VAR1}
